#!/usr/bin/env bash
# CiaNet v2.8.7 — Universal Installer
# این اسکریپت روی هر سرور اوبونتو/دبیان کار می‌کنه — بدون عیب‌یابی.
#
# روش استفاده:
#   sudo bash install.sh
#
# مراحل:
#   ۱) نصب پیش‌نیازها (python, git, sqlite, cloudflared)
#   ۲) clone کردن repo
#   ۳) ساخت venv
#   ۴) ساخت user cianet
#   ۵) ساخت /etc/selfbot.env با ADMIN_ID و ADMIN_BOT_TOKEN
#   ۶) ساخت systemd service با EnvironmentFile
#   ۷) ساخت nginx config (optional)
#   ۸) start سرویس
#
set -e

# رنگ‌ها
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m'

print_step() {
    echo -e "${BLUE}▶ $1${NC}"
}
print_ok() {
    echo -e "${GREEN}✅ $1${NC}"
}
print_warn() {
    echo -e "${YELLOW}⚠️  $1${NC}"
}
print_err() {
    echo -e "${RED}❌ $1${NC}"
}

# ─── Check root ───
if [ "$(id -u)" != "0" ]; then
    print_err "باید با sudo اجرا کنی: sudo bash $0"
    exit 1
fi

INSTALL_DIR="/opt/cianet"
SERVICE_NAME="selfbot"
VENV_DIR="$INSTALL_DIR/.venv"
REPO_URL="https://github.com/DLSDT/CiaNet.ir.git"

echo ""
echo "═══════════════════════════════════════════════════════"
echo "  CiaNet v2.8.7 — Universal Installer"
echo "═══════════════════════════════════════════════════════"
echo ""

# ─── Get credentials from user ───
print_step "تنظیمات اولیه"
read -p "آیدی عددی تلگرام شما (از @userinfobot بپرس): " ADMIN_ID_INPUT
read -p "توکن ربات ادمین (از @BotFather): " ADMIN_BOT_TOKEN_INPUT
read -p "api_id (از my.telegram.org): " API_ID_INPUT
read -p "api_hash (از my.telegram.org): " API_HASH_INPUT
read -p "نام کاربری پنل ادمین وب (default: admin): " PANEL_ADMIN_USER_INPUT
PANEL_ADMIN_USER_INPUT=${PANEL_ADMIN_USER_INPUT:-admin}
read -p "پسورد پنل ادمین وب: " PANEL_ADMIN_PASS_INPUT
read -p "دامنه‌ی پنل (مثلاً panel.yourdomain.ir — اگه نداری، خالی بذار): " PANEL_DOMAIN_INPUT

if [ -z "$ADMIN_ID_INPUT" ] || [ -z "$ADMIN_BOT_TOKEN_INPUT" ] || [ -z "$API_ID_INPUT" ] || [ -z "$API_HASH_INPUT" ]; then
    print_err "همه‌ی فیلدها (به‌جز دامنه) اجباری هستن"
    exit 1
fi

# ─── Install dependencies ───
print_step "نصب پیش‌نیازها..."
apt-get update -y >/dev/null 2>&1
apt-get install -y python3 python3-pip python3-venv git sqlite3 curl nginx >/dev/null 2>&1
print_ok "پیش‌نیازها نصب شدند"

# ─── Create cianet user ───
print_step "ساخت user cianet..."
if ! id "cianet" &>/dev/null; then
    useradd -r -m -d "$INSTALL_DIR" -s /bin/bash cianet
    print_ok "user cianet ساخته شد"
else
    print_warn "user cianet از قبل وجود دارد"
fi

# ─── Clone repo ───
print_step "clone کردن repo..."
if [ -d "$INSTALL_DIR/.git" ]; then
    cd "$INSTALL_DIR"
    sudo -u cianet git fetch origin >/dev/null 2>&1
    sudo -u cianet git reset --hard origin/main >/dev/null 2>&1
    print_ok "repo آپدیت شد"
else
    rm -rf "$INSTALL_DIR"
    git clone "$REPO_URL" "$INSTALL_DIR" >/dev/null 2>&1
    chown -R cianet:cianet "$INSTALL_DIR"
    print_ok "repo کلون شد"
fi

# ─── Create venv ───
print_step "ساخت venv..."
if [ ! -d "$VENV_DIR" ]; then
    sudo -u cianet python3 -m venv "$VENV_DIR"
fi
sudo -u cianet "$VENV_DIR/bin/pip" install --upgrade pip >/dev/null 2>&1
sudo -u cianet "$VENV_DIR/bin/pip" install -r "$INSTALL_DIR/requirements.txt" >/dev/null 2>&1
print_ok "venv ساخته شد و پیش‌نیازها نصب شدند"

# ─── Create /etc/selfbot.env ───
print_step "ساخت /etc/selfbot.env..."
ENV_FILE="/etc/selfbot.env"

# Hash password
PASS_HASH=$(echo -n "$PANEL_ADMIN_PASS_INPUT" | sha256sum | awk '{print "sha256:"$1}')

cat > "$ENV_FILE" << EOF
# CiaNet environment — generated by install.sh
API_ID=$API_ID_INPUT
API_HASH=$API_HASH_INPUT
ADMIN_BOT_TOKEN=$ADMIN_BOT_TOKEN_INPUT
ADMIN_ID=$ADMIN_ID_INPUT
PANEL_ADMIN_USER=$PANEL_ADMIN_USER_INPUT
PANEL_ADMIN_PASS_HASH=$PASS_HASH
PANEL_SESSION_SECRET=$(python3 -c "import secrets; print(secrets.token_hex(48))")
PANEL_CORS_ORIGINS=http://localhost:8000
EOF
if [ -n "$PANEL_DOMAIN_INPUT" ]; then
    echo "PANEL_URL=https://$PANEL_DOMAIN_INPUT" >> "$ENV_FILE"
fi
chmod 600 "$ENV_FILE"
chown cianet:cianet "$ENV_FILE"
print_ok "env file ساخته شد"

# ─── Create systemd service ───
print_step "ساخت systemd service..."
SERVICE_FILE="/etc/systemd/system/${SERVICE_NAME}.service"
cat > "$SERVICE_FILE" << 'EOF'
[Unit]
Description=CiaNet Telegram Selfbot
After=network-online.target
Wants=network-online.target
StartLimitBurst=10
StartLimitIntervalSec=300

[Service]
Type=simple
User=cianet
Group=cianet
WorkingDirectory=/opt/cianet
Environment=HOME=/opt/cianet
EnvironmentFile=/etc/selfbot.env
ExecStart=/opt/cianet/.venv/bin/python -u main.py all
Restart=always
RestartSec=10
StandardOutput=journal
StandardError=journal
SyslogIdentifier=selfbot

[Install]
WantedBy=multi-user.target
EOF
systemctl daemon-reload
systemctl enable "$SERVICE_NAME"
print_ok "service ساخته شد"

# ─── v2.9.5: Install polkit rule so cianet user can restart the service ───
print_step "نصب polkit rule برای auto-update..."
POLKIT_FILE="/etc/polkit-1/rules.d/49-cianet.rules"
cat > "$POLKIT_FILE" << 'POLKIT'
// CiaNet: allow cianet user to restart/stop/start the selfbot service
polkit.addRule(function(action, subject) {
    if (action.id == "org.freedesktop.systemd1.manage-units" &&
        subject.user == "cianet" &&
        action.lookup("unit") == "selfbot.service" &&
        ["start", "stop", "restart"].indexOf(action.lookup("verb")) >= 0) {
        return polkit.Result.YES;
    }
});
POLKIT
chmod 644 "$POLKIT_FILE"
print_ok "polkit rule نصب شد — auto-update حالا کار می‌کنه"

# ─── Start service ───
print_step "شروع سرویس..."
systemctl start "$SERVICE_NAME"
sleep 5
if systemctl is-active --quiet "$SERVICE_NAME"; then
    print_ok "سرویس روشن شد"
else
    print_err "سرویس روشن نشد — لاگ‌ها:"
    journalctl -u "$SERVICE_NAME" --since "10 seconds ago" --no-pager | tail -20
    exit 1
fi

# ─── Show final status ───
echo ""
echo "═══════════════════════════════════════════════════════"
print_ok "نصب کامل شد!"
echo "═══════════════════════════════════════════════════════"
echo ""
echo "📊 آخرین لاگ‌ها:"
journalctl -u "$SERVICE_NAME" --since "10 seconds ago" --no-pager | tail -15
echo ""
echo "🌐 پنل وب:"
if [ -n "$PANEL_DOMAIN_INPUT" ]; then
    echo "   https://$PANEL_DOMAIN_INPUT/u/login.html"
else
    echo "   http://localhost:8000/u/login.html"
fi
echo ""
echo "🤖 ربات تلگرام:"
echo "   با آیدی $ADMIN_ID_INPUT مالک هستی — /start بزن"
echo ""
echo "📋 مراحل بعدی:"
echo "   ۱. /start بزن تو تلگرام"
echo "   ۲. «👤 حساب کاربری» → «📱 لاگین کردن سلف»"
echo "   ۳. شماره موبایل + کد تلگرام بزن"
echo "   ۴. اگه ۲FA داری، پسورد بزن"
echo "   ۵. اکانت وصل می‌شه!"
echo ""
if [ -n "$PANEL_DOMAIN_INPUT" ]; then
    echo "🌐 برای دسترسی از بیرون، Cloudflare Tunnel یا nginx proxy تنظیم کن:"
    echo "   sudo apt install cloudflared"
    echo "   sudo cloudflared tunnel login"
    echo "   sudo cloudflared tunnel create cianet"
    echo "   sudo cloudflared tunnel route dns cianet $PANEL_DOMAIN_INPUT"
    echo "   # config.yml: ingress from $PANEL_DOMAIN_INPUT → http://localhost:8000"
fi
